### PR TITLE
feat(explorer): add integration tests for new example json files

### LINKED ISSUE #1646: [angular] a2ui_explorer is broken
When attempting to run Angular's `a2ui_explorer`, there's compilation errors:

```
Generated examples to a2ui_explorer/src/app/generated/examples-bundle.ts
Application bundle generation failed. [3.941 seconds] - 2026-06-13T03:04:03.204Z

▲ [WARNING] TypeScript compiler options 'module' values 'CommonJS', 'UMD', 'System' and 'AMD' are not supported. [plugin angular-compiler]

  The 'module' option will be set to 'ES2022' instead.


✘ [ERROR] TS2307: Cannot find module 'src/v0_8/types' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/agent-stub-v08.service.ts:20:36:
      20 │ import {ServerToClientMessage} from 'src/v0_8/types';
         ╵                                     ~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'src/v0_8/types' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/agent-stub.service.ts:19:36:
      19 │ import {ServerToClientMessage} from 'src/v0_8/types';
         ╵                                     ~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'src/v0_9/core/catalog_component' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:19:31:
      19 │ import {CatalogComponent} from 'src/v0_9/core/catalog_component';
         ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:43:16:
      43 │       <label>{{ props()['label']?.value() || 'Value' }}: {{ props(...
         ╵                 ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:43:60:
      43 │ ...']?.value() || 'Value' }}: {{ props()['value']?.value() }}</label>
         ╵                                  ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:46:15:
      46 │         [min]="props()['min']?.value() || 0"
         ╵                ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:47:15:
      47 │         [max]="props()['max']?.value() || 100"
         ╵                ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:48:17:
      48 │         [value]="props()['value']?.value() || 0"
         ╵                  ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:70:9:
      70 │     this.props()['value']?.onUpdate(val);
         ╵          ~~~~~


✘ [ERROR] TS2322: Type '{ component: typeof CustomSliderComponent; name: string; schema: any; }' is not assignable to type 'AngularComponentImplementation'.
  The types returned by 'new component(...)' are incompatible between these types.
    Type 'CustomSliderComponent' is missing the following properties from type 'CatalogComponentInstance': props, surfaceId, componentId, dataContextPath [plugin angular-compiler]

    a2ui_explorer/src/app/demo-catalog.ts:49:24:
      49 │       extraComponents: [customSliderComponentDeclaration],
         ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'src/v0_8/types' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/types.ts:18:36:
      18 │ import {ServerToClientMessage} from 'src/v0_8/types';
         ╵                                     ~~~~~~~~~~~~~~~~
```

And the application doesn't start.

This was bisected to commit https://github.com/a2ui-project/a2ui/commit/85381fcc3d366d158396bd9bfbb765f3376923ee, which updated `renderers/angular/tsconfig.json` [here](https://github.com/a2ui-project/a2ui/pull/1616/changes#diff-0f492e0913e47213b36fdee4eeab29663a07e5557213765b351d05515d31ff73).

## Steps to reproduce

1. On branch `main`
2. Run `yarn clean && yarn install && yarn build && yarn demo` on `renderers/angular`

## Expected 

* The `a2ui_explorer` app starts

## Actual

* The app doesn't compile

### PR DESCRIPTION
**Pull request by josemontespg**
Adds explorer integration tests for the new example json files in angular, lit, and react. Relates to #1497.

Fixes #1646

### CODE REVIEW

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_formatted-text.spec.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    textContent = getCanvas().textContent || '';
+  });
+
+  it('should render expected text content', async () => {
+    expect(textContent).toContain('Type something:');
+    expect(textContent).toContain('Formatted output:');
+  });
+
+  it('should update result text when typing in the input field', async () => {
+    const input = fixture.nativeElement.querySelector('input');
```
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_formatted-text.spec.ts]: Agent: Do this.

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_incremental.spec.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+
+  it('should render expected restaurants', async () => {
+    expect(textContent).toContain('The Golden Fork');
+    expect(textContent).toContain("Ocean's Bounty");
+    expect(textContent).toContain('Pizzeria Roma');
+    expect(textContent).toContain('Spice Route');
+  });
+
+  it('should render Book now button for each restaurant', async () => {
+    const buttons = fixture.nativeElement.querySelectorAll('a2ui-v09-button button');
```
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_incremental.spec.ts]: Agent: Do this

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_interactive-button.spec.ts [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+  it('should render expected text content', async () => {
+    expect(textContent).toContain('Click the button below');
+    expect(textContent).toContain('Click Me');
+  });
+
+  it('should dispatch button_clicked action on button click', async () => {
+    const component = fixture.componentInstance;
+
+    const buttons = fixture.nativeElement.querySelectorAll('a2ui-v09-button button');
```
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_interactive-button.spec.ts]: Do this

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_simple-login-form.spec.ts [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+
+  it('should render expected text content', async () => {
+    expect(textContent).toContain('Login');
+    expect(textContent).toContain('Sign In');
+  });
+
+  it('should dispatch login_submitted action with the form contents on button click', async () => {
+    const component = fixture.componentInstance;
+
+    const inputs = fixture.nativeElement.querySelectorAll('input');
```
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_simple-login-form.spec.ts]: Agent: do this

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_formatted-text.spec.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_formatted-text.spec.ts]: 🤖 Applied the suggestion to cast querySelector('input') to HTMLInputElement.

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_incremental.spec.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_incremental.spec.ts]: 🤖 Applied the suggestion to query '.a2ui-button' instead of 'button' and cast to NodeListOf<HTMLButtonElement>.

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_interactive-button.spec.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_interactive-button.spec.ts]: 🤖 Applied the suggestion to query '.a2ui-button' instead of 'button' and cast to NodeListOf<HTMLButtonElement>.

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_simple-login-form.spec.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_simple-login-form.spec.ts]: 🤖 Applied the suggestion to query 'input' and cast to NodeListOf<HTMLInputElement>, and also cast the buttons query to NodeListOf<HTMLButtonElement>.

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_complex-layout.spec.ts [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+ * limitations under the License.
+ */
+
+import {getCanvas, loadExample} from '../utils';
+
+describe('Example: Complex Layout', () => {
+  let textContent: string;
+
+  beforeEach(async () => {
+    await loadExample('Complex Layout');
```
Comment (ditman) [inline renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_complex-layout.spec.ts:23]: Oof, we need to load the example from the filename instead of the title, so it's easier to map between the two. This is not blocking.

File: renderers/angular/a2ui_explorer/src/app/custom-slider.component.ts [hunk 6]
```diff
@@ -16,7 +16,7 @@
 
 import {Component, ChangeDetectionStrategy} from '@angular/core';
 import {CommonModule} from '@angular/common';
-import {CatalogComponent} from 'src/v0_9/core/catalog_component';
+import {CatalogComponent} from '@a2ui/angular/v0_9';
```
Comment (ditman) [inline renderers/angular/a2ui_explorer/src/app/custom-slider.component.ts:19]: Good catch

File: renderers/angular/tsconfig.json [hunk 7]
```diff
@@ -1,6 +1,7 @@
 {
   "compileOnSave": false,
   "compilerOptions": {
+    "baseUrl": ".",
```
Comment (ditman) [inline renderers/angular/tsconfig.json:4]: This change may be fixing this issue:

* https://github.com/a2ui-project/a2ui/issues/1646

If you can start the angular a2ui_explorer after this locally, can you link #1646 to this PR so it gets resolved when this lands?

File: renderers/react/a2ui_explorer/tests/v0_9/00_formatted-text.test.tsx [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+
+  afterEach(async () => {
+    await cleanup();
+  });
+  let textContent: string;
+
+  beforeEach(async () => {
+    container = await loadExample('00_formatted-text.json');
+    surface = getSurface(container);
+    textContent = surface.textContent || '';
```
Comment (ditman) [inline renderers/react/a2ui_explorer/tests/v0_9/00_formatted-text.test.tsx:45]: I don't think we need to `|| ''`, but ok!

**Review by ditman — APPROVED** [review]
This LGTM! If CI is happy, I'm happy!

File: renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_complex-layout.spec.ts (hunk 5 above)
Comment (josemontespg) [reply renderers/angular/a2ui_explorer/src/app/tests/v0_9/00_complex-layout.spec.ts:23]: Yes, not ideal I agree. I would really like to have a way to import the file directly, instead of using the name or an identifier. Out of scope to improve this in this PR though.

File: renderers/angular/tsconfig.json (hunk 7 above)
Comment (josemontespg) [reply renderers/angular/tsconfig.json:4]: Yes!

File: renderers/react/a2ui_explorer/tests/v0_9/00_formatted-text.test.tsx (hunk 8 above)
Comment (josemontespg) [reply renderers/react/a2ui_explorer/tests/v0_9/00_formatted-text.test.tsx:45]: I don't mind either way, keeping it for simplicity of merging this PR.

**Comment by ditman** [comment]
@josemontespg are we waiting for anything to land this?
