### ISSUE TITLE
[angular] a2ui_explorer is broken

### ISSUE THREAD

**Issue by ditman** [google/A2UI#1646]
When attempting to run Angular's `a2ui_explorer`, there's compilation errors:

```
Generated examples to a2ui_explorer/src/app/generated/examples-bundle.ts
Application bundle generation failed. [3.941 seconds] - 2026-06-13T03:04:03.204Z

▲ [WARNING] TypeScript compiler options 'module' values 'CommonJS', 'UMD', 'System' and 'AMD' are not supported. [plugin angular-compiler]

  The 'module' option will be set to 'ES2022' instead.


✘ [ERROR] TS2307: Cannot find module 'src/v0_8/types' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/agent-stub-v08.service.ts:20:36:
      20 │ import {ServerToClientMessage} from 'src/v0_8/types';
         ╵                                     ~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'src/v0_8/types' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/agent-stub.service.ts:19:36:
      19 │ import {ServerToClientMessage} from 'src/v0_8/types';
         ╵                                     ~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'src/v0_9/core/catalog_component' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:19:31:
      19 │ import {CatalogComponent} from 'src/v0_9/core/catalog_component';
         ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:43:16:
      43 │       <label>{{ props()['label']?.value() || 'Value' }}: {{ props(...
         ╵                 ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:43:60:
      43 │ ...']?.value() || 'Value' }}: {{ props()['value']?.value() }}</label>
         ╵                                  ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:46:15:
      46 │         [min]="props()['min']?.value() || 0"
         ╵                ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:47:15:
      47 │         [max]="props()['max']?.value() || 100"
         ╵                ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:48:17:
      48 │         [value]="props()['value']?.value() || 0"
         ╵                  ~~~~~


✘ [ERROR] TS2339: Property 'props' does not exist on type 'CustomSliderComponent'. [plugin angular-compiler]

    a2ui_explorer/src/app/custom-slider.component.ts:70:9:
      70 │     this.props()['value']?.onUpdate(val);
         ╵          ~~~~~


✘ [ERROR] TS2322: Type '{ component: typeof CustomSliderComponent; name: string; schema: any; }' is not assignable to type 'AngularComponentImplementation'.
  The types returned by 'new component(...)' are incompatible between these types.
    Type 'CustomSliderComponent' is missing the following properties from type 'CatalogComponentInstance': props, surfaceId, componentId, dataContextPath [plugin angular-compiler]

    a2ui_explorer/src/app/demo-catalog.ts:49:24:
      49 │       extraComponents: [customSliderComponentDeclaration],
         ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'src/v0_8/types' or its corresponding type declarations. [plugin angular-compiler]

    a2ui_explorer/src/app/types.ts:18:36:
      18 │ import {ServerToClientMessage} from 'src/v0_8/types';
         ╵                                     ~~~~~~~~~~~~~~~~
```

And the application doesn't start.

This was bisected to commit https://github.com/a2ui-project/a2ui/commit/85381fcc3d366d158396bd9bfbb765f3376923ee, which updated `renderers/angular/tsconfig.json` [here](https://github.com/a2ui-project/a2ui/pull/1616/changes#diff-0f492e0913e47213b36fdee4eeab29663a07e5557213765b351d05515d31ff73).

## Steps to reproduce

1. On branch `main`
2. Run `yarn clean && yarn install && yarn build && yarn demo` on `renderers/angular`

## Expected 

* The `a2ui_explorer` app starts

## Actual

* The app doesn't compile

**Comment by gspencergoog** [comment]
Triaged as P1. CCing @josemontesp as the component owner.

**Comment by ditman** [comment]
There's a fix incoming (#1702)

**Comment by josemontespg** [comment]
#1702 Just landed. This should be working now
